name: Release Build

on:
  push:
    tags:
      - 'v*' # 触发标签格式为 v1.0.0 这样的版本号

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: true
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o build/zaproxy-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o build/zaproxy-linux-arm64
        
      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o build/zaproxy-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o build/zaproxy-windows-arm64.exe

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            build/zaproxy-linux-amd64
            build/zaproxy-linux-arm64
            build/zaproxy-windows-amd64.exe
            build/zaproxy-windows-arm64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/
          retention-days: 5